//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPayment4u.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyType
    {
        public CurrencyType()
        {
            this.MobilePlanes = new HashSet<MobilePlane>();
        }
    
        public int CurrencyTypeID { get; set; }
        public string CurrencyType1 { get; set; }
        public string CurrencyTypeDesc { get; set; }
    
        public virtual ICollection<MobilePlane> MobilePlanes { get; set; }
    }
}
