//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPayment4u.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilePlane
    {
        public int MobilePlaneID { get; set; }
        public int MobilePlaneTypeID { get; set; }
        public string MobilePlaneDescription { get; set; }
        public int TalkTime { get; set; }
        public int Validity { get; set; }
        public int Amount { get; set; }
        public int CurrencyTypeID { get; set; }
    
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual MobilePlaneType MobilePlaneType { get; set; }
    }
}
