//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPayment4u.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobleConnectionType
    {
        public MobleConnectionType()
        {
            this.Operators = new HashSet<Operator>();
        }
    
        public int MobleConnectionTypeID { get; set; }
        public string MobleConnectionType1 { get; set; }
        public string MobleConnectionTypeDesc { get; set; }
    
        public virtual ICollection<Operator> Operators { get; set; }
    }
}
