//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPayment4u.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public Operator()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int OperatorID { get; set; }
        public string OperatorName { get; set; }
        public string OperatorDescription { get; set; }
        public int MobileConnectionTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public int LocationID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual MobleConnectionType MobleConnectionType { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
